// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";

// Load .env then .env.local (local overrides) so Prisma sees DATABASE_URL from either
dotenv.config();
dotenv.config({ path: ".env.local" });

import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl?.trim()) {
  throw new Error(
    "DATABASE_URL is required for Prisma. Set it in .env (e.g. your Supabase connection string). See ENV_SETUP_REFERENCE.md or GET_SUPABASE_CONNECTION_STRING.md."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
